### ISSUE TITLE
[BUG] rgba is limited from :style in yuck

### ISSUE THREAD

**Issue by ArtemSmaznov** [elkowar/eww#1040]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Is there a reason why rgba() behaves differently between cscc and yuck?

This works fine:
```scss
.music-player {
    background: rgba(#FF0000, 0.4);
}
```

This for some reason doesn't:
```yuck
(box :class "music-player"
     :style "background: rgba(#FF0000, 0.4);"
```

It works fine without the opacity though:
```yuck
(box :class "music-player"
     :style "background: #FF0000;"
```

To clarify what I am trying to do.
I have a var `music-player-album-color` in yuck and I want to make the music player widget have a dynamic color AND be semi-transparent. I can get to having either one of those but not both.

I have even tried setting a new scss variable from yuck but it seems anything set there operates on a different scope than what I write in scss so couldn't get this working as a workaround.

Is there a bug in how rgba() in handled from yuck or is this a limitation that is easy to overcome?

### Reproducing the issue

Add the following to any widget
```
     :style "background: rgba(#FF0000, 0.4);"
```

### Expected behaviour

the widget should get colored accordingly (40% transparent red)

**Comment by ArtemSmaznov** [comment]
Thanks @ovalkonia for the explanation, it is very informative.
I didn't want to use `:css` property as that would require me to specify the class again and I am not a fan of needless duplication.
For the time being I just changed my script that sets eww variable to output color in the `255, 0, 0` format instead of `#FF0000` one and it is working for me with the `:style` propery. I would like to still use the hex format though with `:style` if possible.
Will give `:css` a try though when I get the chance to see if I'd like that.

**Comment by ovalkonia** [comment]
I don't think you are actually required to specify the class again with the `:css` property. Take a look at the code that handles both `:css` and `:style` properties:
![code](https://github.com/elkowar/eww/assets/60359793/9034b528-ab44-406a-a54a-80276fc84beb)
Here the only thing that differs between those two is the argument in the `load_from_data` method call. So `:style "background: rgba($FF0000, 0.4);"` would result in the argument being literally `"* { background: rgba($FF0000, 0.4); }"`, with literal asterisk. If you want the `:css` property to behave the exact same way `:style` does but with SCSS support, just put it in the brackets here `"* {  }"`. That's why `:style "background: rgba($FF0000, 0.4);"` and `:css "* { background: rgba($FF0000, 0.4); }"` should work exactly the same, just with the SCSS support.

Well, it's still not as clean as with the `:style` property, you have to repeat this `* {  }` pattern, but still not as bad as typing out you class name over and over again. It's up you what to use, but here's a possible way to do it

**Comment by ArtemSmaznov** [comment]
Ah I see, I expected `*` to apply to all widgets so I never tried it. Will give it a go shortly.

**Comment by ArtemSmaznov** [comment]
yeap, I updated my script to output hex colors again and with this I don't see any difference, meaning I am happy:
```
                ;; :style "background: rgba(${music-album-cover-color}, 0.6);"
                :css "* { background: rgba(${music-album-cover-color}, 0.6); }"
```

**Comment by ovalkonia** [comment]
Awesome! I have no idea why the `:style` property doesn't compile the data into CSS using the `grass` crate as `:css` does. Vanilla CSS would work just fine either way. I will make a pull request, in case it wasn't intentional, and we'll see
