### ISSUE TITLE
[BUG] EWW_NET is all 0

### ISSUE THREAD

**Issue by danjenson** [elkowar/eww#1070]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

`EWW_NET` magic variable return 0 for all interfaces, despite `btop` showing traffic and ping explicitly run to create traffic on target interface.

![image](https://github.com/elkowar/eww/assets/4793438/7e978b7b-9fdb-4c0b-9e38-ea850c1930a5)

### Reproducing the issue

Just updated to the most recent version of `eww`.

### Expected behaviour

`EWW_NET` should be populated.

**Comment by hertg** [comment]
Can confirm, updated to version `0.5.0` and got this bug, same for the latest git commit

**Comment by harshkhandeparkar** [comment]
This seems like an issue with the [`sysinfo`](https://github.com/GuillaumeGomez/sysinfo) crate. I tried logging the `old_rx_bytes` and `rx_bytes` the crate keeps track of to find the number of bytes received since the last refresh and they were equal. Can anyone confirm whether this is true so we can open an issue in the upstream repo?

In the meantime, we can keep track of the total bytes received (which is correct), and calculate the difference in eww. The total bytes could also be exported in the `EWW_NET` magic var this way.

**Comment by harshkhandeparkar** [comment]
Another workaround would be to get the total bytes before and after running the `networks.refresh()`.

**Comment by mario-kr** [comment]
I had a look at the source code of the sysinfo crate.
It seems both the `refresh` and `refresh_list` functions on the `Networks` struct update the data.

eww (via https://github.com/elkowar/eww/blob/d1fde927d2799211f791e7ea01cffb667c4f2b60/crates/eww/src/config/system_stats.rs#L211) calls both right after each other.

The fix would be deleting one of those function calls.

`refresh_list` also updates the list of interfaces. Those rarely change on a typical system, but keeping `refresh_list` would be closer to the behaviour pre 0.5.0.

`refresh` only updates the data for the currently known interfaces, which might perform slightly better, but probably only negligible.

**Comment by mario-kr** [comment]
Well, both 0.5.0 and 0.6.0 are affected, because the bugfix landed after the release of 0.6.0.
You can either build eww yourself from the current main-branch, or friendly ask the maintainer to make a 0.7.0 release. Though, depending on your distribution, it might take some time for the eww-package to be updated to the newest release.

**Comment by mhiuuu** [comment]
Thank you so much for such a fast response! It's gonna take a while until the maintainer upgrade the package so I think I will find a workaround!
