### ISSUE TITLE
[BUG]  Tooltip Not Displaying

### ISSUE THREAD

**Issue by KhalidWKhedr** [elkowar/eww#1256]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Tooltip doesn't display. Widgets/Bar are working but the tooltip refuses to render. Was working before. 

### Reproducing the issue

Just doesn't work/ 

### Expected behaviour

Tooltip should display.

### Additional context

Was working fine, then a couple more widgets later tooltips just stopped appearing. 

### Platform and environment

Hyprland: V0.46.0-18-g71dc9f61
Archlinux - 6.12.6-zen1-1-zen
Eww: eww 0.6.0-1 (from aur)

**Comment by hypernova7** [comment]
That behavior is because one of your scripts that you use with deflisten or defpoll has an infinite loop without pauses which causes the tooltip not to be rendered because the system prioritizes resources for the infinite loop of your script that constantly updates the widget that uses it, you can add sleep 1 to your scripts or simply update the variable only when it's really necessary. I had already experienced that problem before and I solved it by adding small pauses to my scripts when there is no need to constantly update, also that will help the script not to waste system resources.

**Comment by KhalidWKhedr** [comment]
Thank you fren. I appreciate you. I'm dumb

**Comment by KhalidWKhedr** [comment]
That behavior is because one of your scripts that you use with deflisten or defpoll has an infinite loop without pauses which causes the tooltip not to be rendered because the system prioritizes resources for the infinite loop of your script that constantly updates the widget that uses it, you can add sleep 1 to your scripts or simply update the variable only when it's really necessary. I had already experienced that problem before and I solved it by adding small pauses to my scripts when there is no need to constantly update, also that will help the script not to waste system resources.

- hypernova7
