### ISSUE TITLE
[FEATURE] Use Rust for config - eww as a rust framework

### ISSUE THREAD

**Issue by SeraphyBR** [elkowar/eww#130]
## Description of the requested feature
I am currently an awesome user and a rust fan, and I believe it would be cool to also be able to write a config for eww using the rust itself, as well as it works in awesome with lua, where it provides its libraries for creating widgets and using lua to program them. The idea would be, instead of using xml, scss and shell scripts, to integrate the 3 into a rust module, where eww would act as a framework

**Comment by legendofmiracles** [comment]
I find this very out of scope, but the implementation par se wouldn't be that hard. 
When the config gets loaded on daemon startup, it gets parsed and then loaded into a struct. I already once had the idea to then just save that struct as binary somewhere and then load that, you wouldn't have to parse everything.
So what you'd have to do is, instead of loading the config, you load some library which you compiled earlier that contains the config. 
~~Or a suckless version, where the config is in the code~~

**Comment by elkowar** [comment]
i mean, thing is - that exists, it's called gtk-rs. If you don't abstract over UI structure with the xml config and don't use shell-scripts for logic - then there is no benefit to using anything other than gtk-rs or some gtk-rs abstraction like relm. Thus, you can just,...use that, and write a rust application. There's nothing that eww could add to that.
