### ISSUE TITLE
Different "types" of sizes

### ISSUE THREAD

**Issue by RossComputerGuy** [elkowar/eww#30]
`pos` and `size`'s `x` and `y` properties should support `%` for a percentage of the screen for the window, `dpi` should also be an option but it should default to pixels. Example:
```
<size x="10%" y="5dpi" />
<pos x="0" y="3%" />
```

**Comment by elkowar** [comment]
how would DPI work? DPI is Dots per inch, and thus a way of quantifying pixel density rather than any kind of size 🤔 
I agree we need to implement `%` for position and size. the main thing that's unclear to me here is how the API with regards to multi-monitor setups should look.
We'd need a way to specify _which_ monitor to display on. Do you have any proposal for an API w.r.t. this? @RossComputerGuy

**Comment by RossComputerGuy** [comment]
Could do `screen="0"` on `<window>` for the primary and then names or numbers, GDK should have an API for getting monitors

**Comment by elkowar** [comment]
Sounds good! Thanks for the feature request.

## Acceptance Criteria for resolving this issue
- [ ] `<window>` supports attribute `screen="<number>"`, which defines the screen that position and size values will be relative to. 
- [ ] `<size>` and `<pos>` in `<window>` support percentages in addition to absolute pixel values. These will then be relative to the screen specified in the `<window>`.

**Comment by RossComputerGuy** [comment]
![screenshot](https://user-images.githubusercontent.com/19699320/96624896-470e3180-12c2-11eb-8d26-4fec3abb3b7b.png)
It seems as if it doesn't take up 100% of the space if `<size>`'s `y` attribute is set to `100%`.

**Comment by elkowar** [comment]
should be fixed now, @RossComputerGuy

**Comment by elkowar** [comment]
should be fixed now, @RossComputerGuy. thanks for bringing it up
