### ISSUE TITLE
Magic variables not listed in magic-vars.md

### ISSUE THREAD

**Issue by Zxmon-code** [elkowar/eww#493]
In the documentation file configuration.md it says, that the magic variables are all listed in magic-vars.md which is not the case

**Comment by viandoxdev** [comment]
The magic vars documentation is generated from the comments in the source (.rs) file, configuration.md says that because it is the case when the docs have been built. The MD files are the source for the docs and are not really meant to be read as is, the built docs are over [here](https://elkowar.github.io/eww/)
