### ISSUE TITLE
[BUG] Widgets reloading when changing workspaces in i3

### ISSUE THREAD

**Issue by AayushSabharwal** [elkowar/eww#506]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Every time I switch workspaces in i3, eww reloads all open windows which causes them to flash momentarily.

### Reproducing the issue

Just opening the example window and switching workspaces triggers this.

### Expected behaviour

Hopefully, it shouldn't reload/flash.

**Comment by elkowar** [comment]
that sounds more like an i3 bug than an eww bug 🤔 eww doesn't care about or even know what workspaces are or what i3 is, so that _shouldn't_ be related to eww. Maybe you have some specific weird config / script that causes your eww widgets to refresh? I'll close this for now, but if you have some specific reason to think this is related to eww, feel free to reopen with more details ^^
