### ISSUE TITLE
[FEATURE] Allow for-loop as a toplevel declaration

### ISSUE THREAD

**Issue by taylor85345** [elkowar/eww#582]
### Description of the requested feature

Allow a for-loop to be used as a toplevel declaration for dynamically generating entire windows or widgets.

### Proposed configuration syntax

```
(for monitor in monitors
  (defwindow bar${monitor}
      :monitor ${monitor}
      (bar_layout)))
```

### Additional context

In my case, I was attempting to dynamically generate copies of my bar based on the indexes of all connected monitors, so that I could have a copy of my bar on each monitor without having multiple, redundant static windows defined in my eww.yuck.

**Comment by elkowar** [comment]
I'm afraid that's not something that's gonna happen any time soon, as window / widget definitions happen in a very different context from actual widget structure. However, for your specific usecase, I've been working on / thinking about ways to allow a window to be opened in several instances, so you could do
`eww open bar --monitor 1 && eww open bar --monitor 2` or something like that, and have two separate instances of the same window open on two different monitors

**Comment by taylor85345** [comment]
Thanks for the tip. I've tried something similar, but last I checked monitor identification seems to be kinda broken in wayland/wlroots. I'll give it another shot.

**Comment by verbalshadow** [comment]
I realize this issue is closed, but I would also would like to see top level for loops.
This would simplify setup in any area where more than one of something can exist (CPUs, Audio sources/sinks, variable monitor setups). Especially where you can't know the number before they are active.

i.e. I have a laptop. Sometime have only the main monitor and other times I plug additional monitors.

I just want to do something like this and make my life and code easier.

```
;; includes
(defpoll monitors "hyprctl monitors -j")

(for mon in monitors
(deflisten workspace${mon.id} "hyprland-workspaces ${mon.name}")
(defwidget workspaces${mon.id} []
  (eventbox :onscroll "hyprctl dispatch workspace `echo {} | sed 's/up/+/\' | sed 's/down/-/'`1"
    (box :class "workspaces"
      (for i in workspace${mon.id}
        (button
          :onclick "hyprctl dispatch workspace ${mon.id}"
          :class "workspace${mon.id}.class"
          "${mon.name}")))))
)
```

**Comment by dtop129** [comment]
I could somehow make the top-level for work by using an esh-templated eww.yuck and regenerating it every time the monitor configuration changes

Relevent section of eww.yuck(made for hyprland)
```
<% i=0; hyprctl -j monitors | jq '.[].id' | while read -r id; do -%>
(defwindow bar<%= $i %>
  :monitor <%= $((i++)) %>
  :geometry (geometry :x "0%" :y "0%" :width "100%" :anchor "top center")
  :stacking "bottom"
  :exclusive true
  (bar :mon_id <%= $id %>)
)
<% done -%>
```

For this to work you need to have `ESH_SHELL=bash` in your environment.
The index `i` is needed since after removing-adding monitors, the hyprland and eww monitors indices don't match anymore.

To update the config I just keep a background script waiting for monitor events on the hyprland socket
