### ISSUE TITLE
Add description of available platforms - MacOS / Windows [FEATURE] 

### ISSUE THREAD

**Issue by sandric** [elkowar/eww#584]
### Description of the requested feature

It would be nice to see where you can use eww - I see from some issues that it should be available on OSX, but I'm not sure, and no information about Windows, would be nice to add it.

### Additional context

Also, could you please tell in this issue is it available only for Linux, or OSX and Windows are also an option, thx.

**Comment by elkowar** [comment]
Eww currently only supports linux. MacOS may happen in the distant future, once either someone commits to continuously maintaining macOS support (possibly in a fork, depending on how big the changes would have to be) or once apple allows developers to target their plattform without needing to buy their hardware. Windows support is very unlikely to ever happen - partially because the platform differences are _way_ too big, and partially because Rainmeter already does a pretty good job replacing paaaaaart of eww, at least
