### ISSUE TITLE
[BUG] eww needs a `sleep` when launching multiple... argh, see details

### ISSUE THREAD

**Issue by Axarva** [elkowar/eww#74]
## Describe the bug
```bash
#!/bin/bash
  eww -d &
  eww open weather_side &
  eww open time_side &
  eww open smol_calendar &
  eww open player_side &
  eww open sys_side &
  eww open sliders_side &
```
This script won't work, or it'll just create only one window instead of all specified.

However, adding a `sleep` command works!
```bash
#!/bin/bash
(eww -d &)
sleep 1
 eww open weather_side &
 eww open time_side &
 eww open smol_calendar &
 eww open player_side &
 eww open sys_side &
 eww open sliders_side &
 ```
 I don't know what we're even looking at, seems like eww needs a delay before launching stuff?

## Reproducing the issue
Run the first script, possibly by using `exec foo.sh` or something along the lines of it.

## Expected behaviour
Launch everything properly

## Additional context
I dunno

**Comment by ahmedkhalf** [comment]
Same bug here! My solution for the maintainers would be to make the `eww daemon` command blocking until the daemon has successfully started.

**Comment by elkowar** [comment]
The current state of this:
`eww daemon` still does not block until it's finished starting, as that would - as stupid as it sounds - be really anoying to implement, from what i can tell.

Generally, it makes sense to run `eww daemon` once, directly on WM startup anyways, in which case it will work.
If you need to wait for eww to start up for some reason, there is now `eww ping` which will exit zero when the eww daemon is reachable, and exit non-zero otherwise. you can use this to poll for eww to have finished initializing.


As I think that the workarounds are solid enough, and as blocking on daemon startup is not gonna happen in the near future (it may at some point, of course), I'll close this.
