### ISSUE TITLE
Building EWW as flake: gtk-layer-shell-0.pc not found

### ISSUE THREAD

**Issue by METROIDHunter9000** [elkowar/eww#775]
Hello, I'm running NixOS and trying to include EWW as a package in my system by using flakes. Here are some relevant code snippets:
Inputs to my `flake.nix`:
```
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    nixpkgs-unstable.url = "nixpkgs/nixos-unstable";

    eww-git.url = "github:elkowar/eww";
  };
```

This is how I add eww to my system packages:
```
  environment.systemPackages = with pkgs; [
    # other stuff...
    inputs.eww-git.packages.x86_64-linux.eww
  ]
```

When I go to build my system with `nixos-rebuild`, nix begins to build eww but stops at this error:
```
error: builder for '/nix/store/77zg2i9azcmgm6wg8c0ql89kkxm4k4xp-eww-e76206817de1cb86ec431dcff7d4b04c8b7d36fc.drv' failed with exit code 101;
       last 10 log lines:
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/77zg2i9azcmgm6wg8c0ql89kkxm4k4xp-eww-e76206817de1cb86ec431dcff7d4b04c8b7d36fc.drv'.
```

Some interesting notes:
1. Installing the wayland package works fine (`inputs.eww-git.packages.x86_64-linux.eww-wayland`)
2. I was able to clone the repository and build it myself. I would run `nix-shell` in the repository's root directory, and then `cargo build --release --no-default-features --features x11` to build EWW. That works.

Looking for assistance regarding this issue. It seems to me like an issue with the `flake.nix` in eww's repository, but I'm not knowledgeable enough in Nix or EWW yet to understand.

Thanks for reading

**Comment by Syudagye** [comment]
Hey, i had a similar issue trying to get #743 working on my configuration.

After some investigation, is seems that the flake in this repository is using the [nixpkgs' expression](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/window-managers/eww/default.nix) and is just putting an overlay into it to build with the files from this repository.
The issue is that since #722 eww builds with wayland support by default, which means it needs `gtk-layer-shell` as a `buildInput` by default. And the nix expression for eww in nixpkgs is still based on eww 0.4.0, which didn't built with wayland support by default, so it do not specify this dependency out of the box.

> Installing the wayland package works fine (inputs.eww-git.packages.x86_64-linux.eww-wayland)

Yes, building `eww-wayland` works fine, and would be the same as building `eww` from now on (if it worked).

> I was able to clone the repository and build it myself. I would run nix-shell in the repository's root directory, and then cargo build --release --no-default-features --features x11 to build EWW. That works.

Same thing here, it works fine with `nix-shell` (using the `shell.nix`).
But with `nix shell` (using `flake.nix` and checking for `devShells` outputs), it fails because it tries to build before starting the shell. As expected, using `nix shell .#eww-wayland` it works just fine too.

<br>

I think the flake in this repo needs to be rewritten to not depend on the nixpkgs' expression, since it's an expression describing the stable version (v0.4.0) of the project, and so it makes it not suitable for standalone usage on the master branch.

I also suggest, since it now default to build with wayland support, using the `eww` package name for building eww with Wayland+X11 support, and `eww-wayland` for Wayland exclusive support.

Not very comfortable with writing flakes just yet, so might need help on this one !
