### ISSUE TITLE
[BUG] Interactable UI elements behave weirdly when their value gets updated from script-vars

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#95]
## Describe the bug
Some UI elements that the user can interact with, i.e. Sliders, will jump around weirdly if their value is being set by both a script-var and the user touching it.

## Reproducing the issue
Create a slider, make it update frequently and move it.

## Expected behaviour
While the user is interacting with the element (i.e. dragging the slider), value updates caused by updates to the `value` attribute should be temporarily ignored, thus allowing the UI to be smooth.

## Implementation Notes
As this applies to multiple widgets, a proper abstraction over this temporary disabling behaviour would be optimal.

As in many cases, the onchange of such an element directly affects the value that the script-var would send (i.e. if the slider is used for volume, moving it will change the system volume, which in turn affects the value that the script-var would have), it may be necessary to add a short delay after the user let go of the widget, such as to give whatever is being controlled a couple milliseconds of time to take effect, as a means of avoiding that the widget state immediately jumps back to an earlier state once let go off.

**Comment by elenapan** [comment]
I wonder if this could be solved by being able to use `onclick` and `onscroll` on the slider.
Just like `onscroll` provides us with `{}` which can be `up` or `down` depending on scroll direction,
`onclick` on a slider could provide us with a value which represents the spot where the user clicks. And then the user is free to do whatever they wish with this value.

The value should be based on the orientation of the slider. If the orientation is horizontal, the value should be the distance from the start of the slider to the place where the click happened on the horizontal axis. Ideally it should be calculated a percentage of the slider's width or height (again, depending on its orientation). For example if the user clicks right in the middle of the slider, `{}` should evaluate to 50.

If that is implemented I believe that `onchange` will not be necessary anymore, since its functionality could be replicated by setting the value of the slider to a variable `var` and setting `eww update var={}` for the `onclick` property. Unless, of course, I am missing something.

P.S. Thank you for working on eww, I am having a ton of fun with it so far.

**Comment by elkowar** [comment]
@elenapan if I understand you correctly, you're proposing to add `onclick` as a callback that only get's called the moment the user clicks, but not while dragging? that would then not really solve the issue, as the issue here is that the value is already being overwritten by whatever script is otherwise controlling the `value` field. Or am I not getting you? 

I should really get to work on this, fixing it by just making eww not apply the script-var update while the slider is being dragged _should_ be reeelatively trivial,...

**Comment by elkowar** [comment]
that should fix it! changes to the value attribute now don't take effect while the slider is being dragged, thus dragging should feel smooth regardless of update rate!
